Version 0.6.2
ITMO-NSS-team/fedot-examples pull request #14
Opened 2023-02-21 19:53 UTC by valer1435

Move notebooks to 0.6.2

2023-02-22 03:27 UTC, andreygetmanov requested changes
Мне кажется, в PR попали временные файлы, которые не должны были в него попадать. Например, multilmodal_history.json совершенно не нужен, это просто результат демонстрации одного метода в примере
Также сомневаюсь в необходимости 2 папок c .ipynb_checkpoints
Не нашёл, где используются сохранённые модели из jupyter_media/models. Если нигде, то тоже можно убрать

2023-02-22 03:27 UTC, andreygetmanov commented on notebooks/latest/7_multimodal_data.ipynb
> +      "ERROR: No matching distribution found for fedot-0.6.2\n",
!pip install fedot==0.6.2

2023-02-22 03:27 UTC, andreygetmanov commented on notebooks/latest/7_multimodal_data.ipynb
> +      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
Имхо, вывод ячейки с установкой Федота неинформативен, поэтому его стоит убрать из ноутбука

2023-02-22 03:27 UTC, andreygetmanov commented on notebooks/latest/1_intro_to_automl.ipynb
> -      "Requirement already satisfied: fedot==0.6.1 in c:\\users\\valery\\appdata\\local\\programs\\python\\python38\\lib\\site-packages (0.6.1)\n",
Если во всех ноутбуках есть этот огромный вывод, имхо, стоит его подчистить

2023-02-24 08:55 UTC, valer1435 commented on notebooks/latest/7_multimodal_data.ipynb
> +      "ERROR: No matching distribution found for fedot-0.6.2\n",
Исправил https://github.com/ITMO-NSS-team/fedot-examples/pull/14/commits/dc97d23dc70d331078a05f7e74e6e190de5af219

2023-02-24 08:55 UTC, valer1435 commented on notebooks/latest/7_multimodal_data.ipynb
> +      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
Убрал везде ячейки https://github.com/ITMO-NSS-team/fedot-examples/pull/14/commits/dc97d23dc70d331078a05f7e74e6e190de5af219

2023-02-24 08:55 UTC, valer1435 commented on notebooks/latest/1_intro_to_automl.ipynb
> -      "Requirement already satisfied: fedot==0.6.1 in c:\\users\\valery\\appdata\\local\\programs\\python\\python38\\lib\\site-packages (0.6.1)\n",
Почистил

2023-02-24 08:55 UTC, valer1435 commented
Убрал лишние файлы

2023-03-07 10:32 UTC, andreygetmanov commented
1. В файле `notebooks/latest/2_intro_to_fedot.ipynb` в ячейке `pipeline.show()` очень большой вывод в консоль перед показом самого графика. Обычно такого нет. Сможешь разобраться в причине и подчистить?
2. Там же в ячейке 16 после обучения зачем-то выводится `OutputData`. Это в целом необязательно, да и выглядит нечитаемо
3. `notebooks/latest/4_auto_ts_forecasting.ipynb` - то же самое, что и в пункте выше (ячейка 9)
4. В примерах 1, 2, 5, 7 можно убрать пустую ячейку в самом конце ноутбука

2023-03-10 09:39 UTC, andreygetmanov commented
Ещё в примере `notebooks/version_06_1/7_multimodal_data.ipynb` добавь версию Федота в `pip install`

2023-03-10 12:35 UTC, andreygetmanov approved these changes

2023-03-10 12:55 UTC, merged