0.7.0
ITMO-NSS-team/fedot-examples pull request #15
Opened 2023-03-11 18:16 UTC by valer1435

Updated examples to 0.7.0

2023-03-11 18:40 UTC, andreygetmanov requested changes
1. В первом примере разница между бейзлайном и Федотом в 0.01. Мб время побольше поставить, чтоб показательнее было?
2. Во всех ячейках, где есть обучение Федота, достаточно объёмный вывод о ходе процесса обучения. Для потенциального юзера это может быть не так информативно + занимает оч много места относительно всего ноутбука. Мб ключевые итоги типа финального пайплайна, метрик и графиков вынести в отдельные ячейки, а вывод обучения Федота просто удалить?

2023-03-13 11:24 UTC, valer1435 commented
> 2. Во всех ячейках, где есть обучение Федота, достаточно объёмный вывод о ходе процесса обучения. Для потенциального юзера это может быть не так информативно + занимает оч много места относительно всего ноутбука. 

ИМХО позволяет пользователю понимать, что все работает и ничего не зависло. А ключевые моменты и правда можно вынести

2023-03-13 11:33 UTC, andreygetmanov commented
> > 2. Во всех ячейках, где есть обучение Федота, достаточно объёмный вывод о ходе процесса обучения. Для потенциального юзера это может быть не так информативно + занимает оч много места относительно всего ноутбука.
> 
> ИМХО позволяет пользователю понимать, что все работает и ничего не зависло. А ключевые моменты и правда можно вынести

Хз, когда вывод консоли занимает ~50% ноутбука (как в примере 2) и просто пролистывается, имхо, это очень неудобно
@nicl-nno рассудишь?

2023-03-13 12:33 UTC, valer1435 commented
> > > 2. Во всех ячейках, где есть обучение Федота, достаточно объёмный вывод о ходе процесса обучения. Для потенциального юзера это может быть не так информативно + занимает оч много места относительно всего ноутбука.
> > 
> > 
> > ИМХО позволяет пользователю понимать, что все работает и ничего не зависло. А ключевые моменты и правда можно вынести
> 
> Хз, когда вывод консоли занимает ~50% ноутбука (как в примере 2) и просто пролистывается, имхо, это очень неудобно @nicl-nno рассудишь?

Можно сделать его а маленьком окошке с отдельным скроллом

2023-03-13 12:41 UTC, andreygetmanov commented
> > > > 2. Во всех ячейках, где есть обучение Федота, достаточно объёмный вывод о ходе процесса обучения. Для потенциального юзера это может быть не так информативно + занимает оч много места относительно всего ноутбука.
> > > 
> > > 
> > > ИМХО позволяет пользователю понимать, что все работает и ничего не зависло. А ключевые моменты и правда можно вынести
> > 
> > 
> > Хз, когда вывод консоли занимает ~50% ноутбука (как в примере 2) и просто пролистывается, имхо, это очень неудобно @nicl-nno рассудишь?
> 
> Можно сделать его а маленьком окошке с отдельным скроллом

Да, согласен

2023-03-20 14:02 UTC, andreygetmanov commented
В примере `evolutionary_diversified_example.ipynb`:
1. Подчисти, пожалуйста, вывод от `!pip install https://github.com/nccr-itmo/FEDOT/archive/master.zip`
2. Ячейки с визуализацией в конце ноутбука не запущены. Так и должно быть?
3. Удали пустую ячейку в конце ноутбука

2023-05-06 17:27 UTC, andreygetmanov approved these changes

2023-05-06 17:31 UTC, merged